#!/bin/bash
#set -e

# ---------------------------------------------
# fill in generic config variables
# ---------------------------------------------
./confd -onetime -backend env

# ---------------------------------------------
# create and configure case
# ---------------------------------------------

# create the case template
chmod a+x ./newcase.sh
./newcase.sh

# fill in some case config files with templated values
./confd -onetime -backend env -confdir /etc/cesm

# read the config files to create run-specific files
cd /var/cesm/case1
mkdir /var/cesm/inputdata
./cesm_setup

# Need these two config files to overwrite the ones generated by cesm_setup
mv /Macros /var/cesm/case1
mv /case1.run /var/cesm/case1

# ---------------------------------------------
# build case
# ---------------------------------------------
ln -s /usr/bin/make /usr/bin/gmake
./case1.build

# ---------------------------------------------
# run case
# ---------------------------------------------
. /etc/profile.d/openlava.sh
service openlava start
chmod +x case1.run
ln -s /usr/libnetcdff.so.6 /usr/lib/libnetcdff.so.6
ln -s /usr/libnetcdf.so.11 /usr/lib/libnetcdf.so.11
# ./case1.run

# ---------------------------------------------
# save results to s3
# ---------------------------------------------

/bin/bash
