#!/bin/bash

#--------------------------------------
# Install Docker and other packages
#--------------------------------------
apt-get update
apt-get install -y apt-transport-https ca-certificates
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y linux-image-extra-$(uname -r) docker-engine python3-pip
docker daemon --storage-opt dm.basesize=90G
service docker restart

pip3 install toml

#--------------------------------------
# Write CESM config vars to file
#--------------------------------------

cesm_vars_file=/cesm_vars.toml

cat <<EOF >$cesm_vars_file
